# Make wheel packages for pyexiv2, and upload them. 

name: release

on:
  workflow_dispatch:
    inputs:
      last_build_id:
        description: Input the run id of workflows/build.yml, to download artifacts from it.
      upload_to_github:
        default: false
      # upload_to_pypi:
      #   default: false

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Download compiled files
      uses: actions/download-artifact@v4
      with:
        # name: *
        path: compiled/
        run-id: ${{ inputs.last_build_id }}

    - name: List compiled files
      run: |
        tree -sh compiled/

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: |
          dist/
        if-no-files-found: error
        retention-days: 3

    - name: Upload to GitHub
      uses: softprops/action-gh-release@v2
      if: inputs.upload_to_github == true
      with:
        name: A draft for release
        draft: true
        body: This release is automatically generated by workflows/release.yml.
        files: |
          dist/

    # - name: Upload to PyPI
    #   if: inputs.upload_to_pypi == true
    #   run: |
    #     python -m pip install twine
    #     python -m twine upload --verbose --skip-existing dist/*
