# Test pyexiv2 wheel packages uploaded to pypi.org .

name: Test package

on:
  # release:
  #   types: [published]
  workflow_dispatch:
    inputs:
      pyexiv2_version:
        default: 2.15.4

jobs:
  on_linux:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - { os: ubuntu-22.04, exiv2_platform_name: Linux-x86_64 }
          - { os: ubuntu-22.04-arm, exiv2_platform_name: Linux-aarch64 }
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.runner.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install pyexiv2==${{ inputs.pyexiv2_version }}
        python -m pip install pytest psutil
    - name: Test
      run: |
        pytest -sv
      env:
        FROM_SOURCE_CODE_IMPORT_PYEXIV2: False

  on_macos:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - { os: macos-13, exiv2_platform_name: Darwin-x86_64 }
          - { os: macos-14, exiv2_platform_name: Darwin-arm64 }
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.runner.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install pyexiv2==${{ inputs.pyexiv2_version }}
        python -m pip install pytest psutil
    - name: Test
      run: |
        brew install inih
        pytest -sv
      env:
        FROM_SOURCE_CODE_IMPORT_PYEXIV2: False

  on_windows:
    strategy:
      fail-fast: false
      matrix:
        runner:
         - { os: windows-2022, exiv2_platform_name: 2022msvc-AMD64 }
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.runner.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install pyexiv2==${{ inputs.pyexiv2_version }}
        python -m pip install pytest psutil
    - name: Test
      run: |
        pytest -sv
      env:
        FROM_SOURCE_CODE_IMPORT_PYEXIV2: False
